import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
	server: {
		CLERK_SECRET_KEY: z.string(),
		CONVEX_DEPLOYMENT: z.string(),
		CLERK_JWT_ISSUER_DOMAIN: z.url(),
		GEMINI_API_KEY: z.string(),
		ANTHROPIC_API_KEY: z.string(),
		INNGEST_DEV: z.string(),
		FIRECRAWL_API_KEY: z.string(),
		SENTRY_AUTH_TOKEN: z.string(),
		CONVEX_SERVICE_TOKEN_SIGNING_JWK: z.string(),
		CONVEX_SERVICE_TOKEN_ISSUER: z.string(),
		CONVEX_SERVICE_TOKEN_AUDIENCE: z.string(),
		CONVEX_SERVICE_TOKEN_KID: z.string(),
		CONVEX_SERVICE_TOKEN_PUBLIC_JWK: z.string(),
	},
	client: {
		NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string(),
		NEXT_PUBLIC_CONVEX_URL: z.url(),
		NEXT_PUBLIC_CONVEX_SITE_URL: z.url(),
		NEXT_PUBLIC_CLERK_SIGN_IN_URL: z.string(),
		NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: z.string(),
	},
	runtimeEnv: {
		CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
		CONVEX_DEPLOYMENT: process.env.CONVEX_DEPLOYMENT,
		CLERK_JWT_ISSUER_DOMAIN: process.env.CLERK_JWT_ISSUER_DOMAIN,
		GEMINI_API_KEY: process.env.GEMINI_API_KEY,
		ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
		INNGEST_DEV: process.env.INNGEST_DEV,
		FIRECRAWL_API_KEY: process.env.FIRECRAWL_API_KEY,
		SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
		CONVEX_SERVICE_TOKEN_SIGNING_JWK:
			process.env.CONVEX_SERVICE_TOKEN_SIGNING_JWK,
		CONVEX_SERVICE_TOKEN_ISSUER: process.env.CONVEX_SERVICE_TOKEN_ISSUER,
		CONVEX_SERVICE_TOKEN_AUDIENCE:
			process.env.CONVEX_SERVICE_TOKEN_AUDIENCE,
		CONVEX_SERVICE_TOKEN_KID: process.env.CONVEX_SERVICE_TOKEN_KID,
		CONVEX_SERVICE_TOKEN_PUBLIC_JWK:
			process.env.CONVEX_SERVICE_TOKEN_PUBLIC_JWK,
		NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
			process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
		NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL,
		NEXT_PUBLIC_CONVEX_SITE_URL: process.env.NEXT_PUBLIC_CONVEX_SITE_URL,
		NEXT_PUBLIC_CLERK_SIGN_IN_URL:
			process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
		NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL:
			process.env.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL,
	},
});
